### ISSUE TITLE
No result returned from netmiko_send_command

### ISSUE THREAD

**Issue by shottadrae** [ktbyers/pynet#25]
I am following the post "Using Nornir for OS Upgrades (Part 2)" to upgrade a switch but at the section of the code to verify the boot variable, I don't get a print out on screen. I tried a couple of things to troubleshoot but haven't figured out the issue. one of my problems is I don't know how to debug :(. As for the testing I've done, I tested that section of the code by itself and it worked fine. i also move it above the set_boot_var task and that worked. so it seems to me something in the set_boot_var function is causing netmiko_send_command to not return a value. interestingly even though it doesn't return a value it still performs the command.  i am using the script "nornir_os_upgrade.py" with few adjustments.

```python
def main():
    print("************** Starting File Transfer *********************")
    # Initialize Nornir object using default "SimpleInventory" plugin
    nr = InitNornir().filter(hostname="172.30.14.5")

    result = nr.run(
        task=os_upgrade,
        num_workers=20,
    )
    std_print(result)

    # Filter to only a single device
    nr_ios = nr.filter(hostname="172.30.14.5")

    aggr_result = nr_ios.run(task=set_boot_var)

    # If setting the boot variable failed (assumes single device at this point)
    for hostname, val in aggr_result.items():
        if val[0].result is False:
            sys.exit("Setting the boot variable failed")
    

    # Verify the boot variable
    result = nr_ios.run(
        task=netmiko_send_command,
        command_string= f'send log "configured from Nornir {time.time()}"', 
        num_workers=20,
    )
    print(result) # print result to see what was returned
    std_print(result) #I dont get a result back
    continue_func()

```

**Result**

--------------------------------------------------
GudeTest2960-X

True
--------------------------------------------------

--------------------------------------------------
GudeTest2960-X

--------------------------------------------------

Any help with this will be appreciated. Thanks.

**Comment by ktbyers** [comment]
What is in your task `set_boot_var`

```
 aggr_result = nr_ios.run(task=set_boot_var)
```

**Comment by shottadrae** [comment]
here is set_boot_var

```python

def set_boot_var(task):
    """
    Set the boot variable for Cisco IOS.
    return True if boot variable set
    return False if staging verification steps failed
    """
    primary_img = task.host.get('img')
    backup_img = task.host.get('backup_img')

    # Check images are on the device
    for img in (primary_img, backup_img):
        result = task.run(
            task=netmiko_send_command,
            command_string=f"dir flash:/{img}"
        )
        output = result[0].result
        # Drop the first line as that line always contains the filename
        output = re.split(r"Directory of.*", output, flags=re.M)[1]
        if img not in output:
            return False

    commands = f"""
default boot system
boot system flash {primary_img}
boot system flash {backup_img}
"""
    command_list = commands.strip().splitlines()
    task.run(
        task=netmiko_send_config,
        config_commands=command_list
    )
    return True


```

**Comment by shottadrae** [comment]
It's working now with no change to the code other than the command I send with Netmiko. I will just call this user error. Sorry for the inconvenience and thank you for your time.
