### ISSUE TITLE
Timeout while Transfering NXOS Bin file!!

### ISSUE THREAD

**Issue by sindhujit** [ktbyers/pynet#26]
Hi Kirk,
The file transfer of a nxos image (e.g.: I7(6).bin) takes longer than expected and it fails with following error:

> paramiko.ssh_exception.SSHException: Key-exchange timed out waiting for key negotiation

Below is complete error :

[complete_error.txt](https://github.com/ktbyers/pynet/files/3522200/complete_error.txt)

Also are you aware of a way to track the progress of the file transfer as a background task, and show them the UI in django?

**Comment by adudek16** [comment]
What happens when you ssh to it?  add -v or multiple (up to 3, ie -vvv).  Probably need to specify an alternate key to match the offer. This happens with newer versions of openssh going to older cisco releases.
