### ISSUE TITLE
pynet/learnpy_ecourse/class1/ex1_ex2_ipv6_split.py solution

### ISSUE THREAD

**Issue by orangecloud1111** [ktbyers/pynet#7]
Hi Kirk,
In the solution for this assignment, when I use the join method, the result is not as I expect it to be. What am I missing?
>>> a
'FE80:0000:0000:0000:0101:A3EF:EE1E:1719'
>>> a.split(":")
['FE80', '0000', '0000', '0000', '0101', 'A3EF', 'EE1E', '1719']
>>> ":".join(a)
'F:E:8:0:::0:0:0:0:::0:0:0:0:::0:0:0:0:::0:1:0:1:::A:3:E:F:::E:E:1:E:::1:7:1:9'

**Comment by ktbyers** [comment]
@orangecloud1111 I didn't see this until now...

a.split(":") does not change a. In other words, when you do your .join(a), a is still a string.

You need to save the a.split(":")

>>> a = 'FE80:0000:0000:0000:0101:A3EF:EE1E:1719'
>>> a.split(':')
['FE80', '0000', '0000', '0000', '0101', 'A3EF', 'EE1E', '1719']
>>> a
'FE80:0000:0000:0000:0101:A3EF:EE1E:1719'
>>> 
>>> new_a = a.split(':')
>>> new_a
['FE80', '0000', '0000', '0000', '0101', 'A3EF', 'EE1E', '1719']
>>> 
>>> ':'.join(new_a)
'FE80:0000:0000:0000:0101:A3EF:EE1E:1719'
